apiVersion: apps/v1
kind: Deployment
metadata:
  name: chatwithpdf
spec:
  replicas: 2
  selector:
    matchLabels:
      app: chatwithpdf
  template:
    metadata:
      labels:
        app: chatwithpdf
    spec:
      containers:
        - name: chatwithpdf
          image: 263323232352.dkr.ecr.ap-south-1.amazonaws.com/gigax01/pdfchatapp:a3f83f86c4d765fc4eab29ce0a2388b1896bb9b1
          ports:
            - containerPort: 3000
          env:
            - name: DATABASE_URL
              valueFrom:
                secretKeyRef:
                  name: chatwithpdf-secrets
                  key: DATABASE_URL
            - name: GOOGLE_CLIENT_ID
              valueFrom:
                secretKeyRef:
                  name: chatwithpdf-secrets
                  key: GOOGLE_CLIENT_ID
            - name: GOOGLE_CLIENT_SECRET
              valueFrom:
                secretKeyRef:
                  name: chatwithpdf-secrets
                  key: GOOGLE_CLIENT_SECRET
            - name: NEXTAUTH_SECRET
              valueFrom:
                secretKeyRef:
                  name: chatwithpdf-secrets
                  key: NEXTAUTH_SECRET
            - name: AWS_ACCESS_KEY_ID
              valueFrom:
                secretKeyRef:
                  name: chatwithpdf-secrets
                  key: AWS_ACCESS_KEY_ID
            - name: AWS_SECRET_ACCESS_KEY
              valueFrom:
                secretKeyRef:
                  name: chatwithpdf-secrets
                  key: AWS_SECRET_ACCESS_KEY
            - name: AWS_REGION
              valueFrom:
                secretKeyRef:
                  name: chatwithpdf-secrets
                  key: AWS_REGION
            - name: AWS_S3_BUCKET
              valueFrom:
                secretKeyRef:
                  name: chatwithpdf-secrets
                  key: AWS_S3_BUCKET
            - name: AWS_BEDROCK_MODEL
              valueFrom:
                secretKeyRef:
                  name: chatwithpdf-secrets
                  key: AWS_BEDROCK_MODEL
            - name: HUGGING_FACE_API
              valueFrom:
                secretKeyRef:
                  name: chatwithpdf-secrets
                  key: HUGGING_FACE_API
            - name: HF_API_KEY
              valueFrom:
                secretKeyRef:
                  name: chatwithpdf-secrets
                  key: HF_API_KEY
            - name: PINECONE_API_KEY_HUGG_EMBDD
              valueFrom:
                secretKeyRef:
                  name: chatwithpdf-secrets
                  key: PINECONE_API_KEY_HUGG_EMBDD
            - name: MODEL_ID
              valueFrom:
                secretKeyRef:
                  name: chatwithpdf-secrets
                  key: MODEL_ID
            - name: MODEL
              valueFrom:
                secretKeyRef:
                  name: chatwithpdf-secrets
                  key: MODEL
---
apiVersion: v1
kind: Service
metadata:
  name: chatwithpdf
spec:
  type: LoadBalancer
  selector:
    app: chatwithpdf
  ports:
    - port: 80
      targetPort: 3000
